### PR TITLE
Correct parse 80211 radiotap header

### PR DESCRIPTION
**Pull request by alexeypertcev**
Fixed parse presents flags ((bitmask & (1 << 31)) == 1 is always false). 
The radiotap fields are naturally aligned, but current implementation ignore it. I didn't find binary reader implementation for support natural alignment and created new NaturalAlignmentBinaryReader class.

### CODE REVIEW

**Comment by chmorgan** [comment]
Hi @alexeypertcev. Good catch on the broken functionality here and the broken unit test.

What is the thought behind the NaturalAlignmentBinaryReader? Why not use the normal binary reader instead to avoid creating a new class?

**Comment by alexeypertcev** [comment]
Hello Chris Morgan,

I don't know how to use BinaryReader for natural alignment. I'm ready to
use other completed decision, If it exist.

About NaturalAlignmentBinaryReader. I can use original BinaryReader and
calculate aligned paddings in each call RadioTapField.Parse method, but
this way need a lot of changes in different files. New class, supporting
natural alignment, is more ellegant on my opinion.

Thank you,
Alexey

2017-09-20 20:15 GMT+03:00 Chris Morgan <notifications@github.com>:

**Comment by chmorgan** [comment]
HI @alexeypertcev, can you explain what natural alignment is and why the BinaryReader won't work? The binaryreader allows for byte, 16, 32, 64bit alignment depending on where you start and how much you read/write. To achieve alignment to 32 bits alignment one would read bytes until they were aligned and then read 32bit at a time. Typically this reading until alignment would occur naturally during the packet parsing process.

**Comment by alexeypertcev** [comment]
Hello Chris Morgan,

Under 'natural alignment' I mean 'Radiotap requires that all fields in the radiotap header are aligned to natural boundaries. For radiotap, that means all 8-, 16-, 32-, and 64-bit fields must begin on 8-, 16-, 32-, and 64-bit boundaries, respectively' (http://www.radiotap.org/)

For example, following part of radiotap header aligned to natural boundaries before tsft flag. And current PacketDotNet implementation (with origin BinaryReader) will read tsft as 4 bytes padding and first 4 bytes of real tsft flag (see 'fake tsft' in 3rd line below), because BinaryReader is nothing know about zero paddings in memory stream.

| hdr_rev | hdr pad | hdr len | present flag | present flag | PADDING | tsft flag | ...
| 1 byte -|- 1 byte -| 2 bytes | - 4 bytes - - | - 4 bytes - - | - 4bytes - -| 8 bytes | ...
| hdr_rev | hdr pad | hdr len | present flag | present flag | - - fake tsft - - |

Also, you can see C implementation [radiotap.c](https://github.com/radiotap/radiotap-library/blob/master/radiotap.c), in line 299 iterator->_arg incremented to padding is it needed.

**Comment by alexeypertcev** [comment]
I'm sorry for changes in pull request. I added unit test with natural alignment and correct NaturalAlignmentBinaryReader. Also, commented Console.Writeline look like typoerror.

**Comment by chmorgan** [comment]
Hi @alexeypertcev. I took a detailed look at these changes and I'm quite confident that something is being missed in the Radiotap parsing that could be properly handled with BinaryReader. My reasoning is that none of this code works at a lower alignment than a byte, so there is no way that the data could be misaligned by 1, 2, 3, 4, 5, 6, or 7 bits, its all aligned to 8 bits. Now clearly there is some alignment issue that is present and I'm confident it can be fixed in a simpler fashion.

If you could include just your new test, TestDoublePresentFlag() as the first commit in your pull request I could pull that in and look at why that might be failing. Imo that is the most valuable thing you could do now that would help us to fix the issue.

We can discuss the other flag checking changes later but without a unit test that works against a captured packet that fails, and then a commit with just those changes that makes it pass its tough to second guess that code, it logically looks correct to me.

**Comment by alexeypertcev** [comment]
Hello Chris Morgan,

I have created new pull request #26 with only one new test case (test fail).

About bit alignment, it isn't requre for radiotap header. Minimal alignment boundares is 1 byte.

**Comment by chmorgan** [comment]
@alexeypertcev thanks for the new PR. I haven't gotten to it yet but I will at some point in the nearish future.

**Pull request closed without merging**
