### PR TITLE
[WIP] Enable setting TCP options

### PR DESCRIPTION
**Pull request by Phyxion**
Most TCP options can now be set, as well as the Options in TcpPacket.

To anyone giving this a try, it DOES NOT increase/decrease the TCP packet size, you will need to so on your own if you add/remove options.

### CODE REVIEW

**Comment by Phyxion** [comment]
Just updated to change tcp options parsing to use existing byte segment. Everything seems to work OK but would like to do some further testing before this should be merged.

**Comment by Phyxion** [comment]
I've been using and testing it for about two weeks now on several PCs, no issues, so LGTM to merge 👍 .

**Comment by Phyxion** [comment]
@chmorgan I've been using it for about two weeks now, no issues, so LGTM to merge 👍 .

**Comment by chmorgan** [comment]
@Phyxion thanks for another PR! Merging now.

**Pull request merged**
