### PR TITLE
Use of this keyword

### PR DESCRIPTION
**Pull request by pluskal**
Use this keyword to differentiate object members from static members and static classes.

This change simplifies readability because of inconsistency in naming conventions of type members and parameters.

### CODE REVIEW

**Comment by chmorgan** [comment]
I'm not convinced we should be adding this. everywhere. It's a boatload of text added and modern IDEs provide easy lookup of variable sources. Doesn't the .net convention of lowercase variables vs. upper case types make this mostly unnecessary?

**Comment by pluskal** [comment]
That depends, I like this because with that keyword I know whether it is object instance member, or static member, or even static class or its member. 

The naming conventions do not cover that, e.g., (protected|public) filed, and all properties should be named with capital letter and that collides the same convention that goes for static fields no matter access modifiers and class, enum and struct. Also, this distinguishes local variable and private field in case that convention for private field is without underscore.

But, it is mostly a matter of personal taste. If you do not like this, I can add it each time for my readability and remove it in future commits.

**Comment by chmorgan** [comment]
@pluskal this does look like a lot of extra characters for not much gain. Now if there are specific confusing instances or inconsistent naming usage that doesn't match the .net standards those are good places to chip away at and resolve. Having to use this. everywhere seems like a lot of extra work when you know from understanding the code what types things are.

Along these lines I did notice some explicit type declarations like Dictionary<xxx,xxx> x = .... that I'll probably end up switching over to use 'var' for clarity. Thoughts?

I think we should sit on this until there is a greater need.

**Comment by pluskal** [comment]
Ok, in that case, I'll be pushing changes for inconsistent naming directly without _this_.

I love _var_ I use it everywhere, so if var is OK with you, let's change it.

**Comment by chmorgan** [comment]
@pluskal I like var because it reduces the number of characters to read and type. PRs welcome!

**Pull request closed without merging**
