### PR TITLE
Version bump + various changes

### PR DESCRIPTION
**Pull request by Phyxion**

### CODE REVIEW

**Comment by Phyxion** [comment]
AppVeyor fails due to missing WinPcap library.

**Comment by chmorgan** [comment]
@Phyxion did you have to add the winpcap dependency? How did the change to .nuspec fix the build?

**Comment by chmorgan** [comment]
@Phyxion oh its still failing... do we need to add winpcap as a dependency?

**Comment by Phyxion** [comment]
For some reason AppVeyor fails at installing winpcap from chocolatey. It's required for running the tests I think. It does work locally. I'll do a another commit and see if it's working now.

**Comment by chmorgan** [comment]
@phyxion interested in commit access to the repo? I’d like to add additional maintainers in case I get hit by a bus and you’ve been active lately. It would still be ideal if you could get approval for all commits prior to their merge to master.

**Comment by Phyxion** [comment]
@chmorgan Yes, sure, that would be fine 👍 I would still do the same with PRs (probably through separate branch then).

As for the `LazyThreadSafetyMode.PublicationOnly` changes, this is still thread-safe, if multiple threads access it at the same time then the first thread to compute the value will set it, the remainder will be discarded. This is enough for the purpose here, as it's not very likely multiple threads will access the payload at the same time (even if it would, the underlying ByteArraySegment would remain the same across threads). Compared to `LazyThreadSafetyMode.ExecutionAndPublication` (the default), this saves about 25% time on create + initial hit. On gbit speeds this is noticable (I saw the Lazy initialization come up in profiler).

**Comment by Phyxion** [comment]
Done, I've updated the commit 👍

**Pull request merged**
