### PR TITLE
Migrate PacketDotNet to .NET Standard 2

### PR DESCRIPTION
**Pull request by pluskal**

### CODE REVIEW

**Comment by pluskal** [comment]
Add Nuget package of SharpPcap after merging [pullrequest](https://github.com/chmorgan/sharppcap/pull/34)

**Comment by haufes** [comment]
The build it failing, it's using MSbuild ver 14. I think if it's changed it to version 15 it will work.

**Comment by chmorgan** [comment]
@haufes the build is set to Visual Studio 17 but I see no MSbuild version setting available in appveyor. Any pointers?

**Comment by haufes** [comment]
I haven't used appveyor, but I saw this earlier.
https://help.appveyor.com/discussions/problems/6894-msbuild-version-for-vs-2017

**Comment by haufes** [comment]
I created a test project and built it on appveyor. It used msbuild 15. I think the only thing I changed after creating the project is build worker image set to Visual Studio 2017

**Comment by cmo-hms** [comment]
@haufes can you share a link to a build of this branch on AppVeyor? I'd like to look at the output etc.

**Comment by chmorgan** [comment]
@haufes can you share a link to the build so I can look at how its building? Are you building this branch?

**Comment by haufes** [comment]
Checkout my PR

**Comment by chmorgan** [comment]
@pluskal I've merged @haufes changes to build .net standard 2.0 and .net framework 4.6.1 (or something like that) to master. Can you rebase against that and update your pull request for any remaining changes that you'd like to merge in?

**Comment by pluskal** [comment]
@chmorgan sure, I'll look into that, but that was roughly what I needed. 

But, my changes were more like a cleanup or coding style ones. Do you want to incorporate it too? Like the unification of naming conventions and C# 6/7 features like expression bodies for short methods, properties and so on?

I tried to do it previously on nonpublic API so it would not break existing code, so I can repeat it.

**Pull request closed without merging**
