### PR TITLE
Bump assembly version and nuspec version from 0.16.0 up to 0.17.0

### PR DESCRIPTION
**Pull request by haufes**

### CODE REVIEW

**Comment by chmorgan** [comment]
@haufes I'll merge this when the stuff with Jan settles down, if its ok that I hold off for a bit longer.

I did have a question for you, how did you add via VisualStudio gui, the configuration settings to build both .net 4.5.1 and .net platform 2.0 builds for PacketDotNet? I'm not seeing the .net 4.5.1 build under VisualStudio for Mac, I see them here with Visual Studio community under Windows but can't find where that is configured in the UI. I'd like to find it there and then report the issue to Visual Studio for Mac.

I also haven't tested under Linux yet but I'm not hopeful given that mono is used for both VS for Mac and Linux.

**Comment by haufes** [comment]
I didn't use the gui, I had to modify the files by hand. I'm not sure that you can, I never found a way to.

**Comment by chmorgan** [comment]
Should we drop building for .net 4.5.1 entirely or do some people require
that? Can you use a .net framework 2.0 assembly with a .net 4.5.1 project?

**Comment by haufes** [comment]
Here is the version matrix for .netstandard. 
https://docs.microsoft.com/en-us/dotnet/standard/net-standard
It we drop 4.5.1 then the latest .net framework supported is 4.6.1.

**Comment by chmorgan** [comment]
What if we drop all .net framework support? Possible to use .net standard
assemblies in a .net framework project? I'd imagine maybe but probably not
if with an old .net framework toolchain.

**Comment by haufes** [comment]
Sure, a .net standard can be using in both .net framework and .net core. But yes would drop support for older frameworks.

**Comment by chmorgan** [comment]
Ahh so it could be used in .net 4.6.1 but not .net 4.5.1?

**Comment by haufes** [comment]
ya. What we can right now works in both.
Is you concern that the projects aren't working well in for some IDEs?

**Comment by chmorgan** [comment]
It is. I'm not able to build the project in VS for Mac as the Test project
and the examples are looking for the .net 4.5.1 (I think that is the
version) .dll. And there is the additional complication that the gui can't
configure those build options. If we switched to .net standard 2.0 as you
and Jan had suggested, then it looks like we'd be ok across Windows, Mac
and Linux and able to configure things via the gui.

A user had requested dropping back to 4.5.1 a number of months ago, July
2017. I'm thinking maybe it has been long enough that we can drop 4.5.1
support and with .net standard 2.0 support 4.6.1.

Thoughts?

**Comment by haufes** [comment]
It's probably ok to drop the .net framework. Anyone that is still developing in 4.5.1 will be forced to upgrade, but that really shouldn't be a big deal.

Oh... apparently MS dropped support for 4.5.1 in 2016-01-12. So I'd say go for it.

**Comment by chmorgan** [comment]
@haufes, @pluskal I'm close to having a resolution that should work. I'm using @pluskal's approach of putting the net451 build first. I'm having trouble running the unit tests under Linux, reported the issue, waiting to see what comes back there. It looks like .net 2.0 support is coming soon too so that can be another option probably in the near future.

**Comment by haufes** [comment]
Sounds good. Sorry, I was busy this week and wasn't really following what is going on.

**Comment by pluskal** [comment]
Nice! I was about to install MonoDevelop and test it, but I am glad you have solved that out.

**Comment by chmorgan** [comment]
Hi @pluskal thanks for the changes.

**Comment by chmorgan** [comment]
And @haufes thanks for these changes!

**Pull request merged**
