### PR TITLE
Misc changes

### PR DESCRIPTION
**Pull request by Phyxion**
NuGet should also be updated 👍

### CODE REVIEW

**Comment by chmorgan** [comment]
This should trigger a NuGet version update automatically as the AppVeyor build is built, at least that's what it should do.

**Comment by Phyxion** [comment]
Great, thanks for the merge, I'll check NuGet later :)

**Comment by chmorgan** [comment]
I just received a NuGet notification about 0.18 being published. We'll see
what feedback people have on the lazy loading changes and other api changes.

**Comment by Phyxion** [comment]
It's already online indeed, great 👍

**Pull request merged**
