### PR TITLE
Teredo

### PR DESCRIPTION
**Pull request by haufes**
Third Pull request in the series
Adding Teredo parsing to the UDP packets class and bumping the version 

Sorry I basic of off my branch and so it included the code from the previous two pull requests

### CODE REVIEW

**Comment by Phyxion** [comment]
Please hold off a little with the PRs until the initial one is merged, this makes reviewing much easier.

**Comment by haufes** [comment]
I'm done for now 😊. Just oldest to newest.

________________________________

**Comment by haufes** [comment]
I've reset of the master branch to break out this PR from the Extended headers

**Comment by Phyxion** [comment]
Closing after #86.

**Pull request closed without merging**
