### PR TITLE
Printing byte arrays

### PR DESCRIPTION
**Pull request by nmiglio**
This fix my issue with the printing of byte arrays

### CODE REVIEW

**Comment by chmorgan** [comment]
It would be clearer if you were to use git rebase and fixup the overlapping commits, eg. rather than introduce .TrimEnd() in one commit and remove it in another one, if the second commit is undoing part of the first you can git rebase, reorder the commits and flag the second as a "fixup" to collapse them together.

Also, can you say "what and why" you are making the change in the commit log subject. The other commits in the project should be reasonable examples of using the first line of the commit message as the "subject" and the rest as the "body" where you can include more details, if necessary/desired.

**Comment by nmiglio** [comment]
In my tests the trim was not needed. I don`t know if the trim makes it cleaner.

sorry for the confusing commits.. still learning how to use git. I'll try to learn from others.

**Comment by chmorgan** [comment]
Any plans to update this pr to squash and clean things up?

**Comment by chmorgan** [comment]
Ping on my comment from Jul 8, 2016.

**Pull request closed without merging**
