### PR TITLE
README.md - Add gitter badge

### PR DESCRIPTION
**Pull request by chmorgan**

### CODE REVIEW

**Comment by Phyxion** [comment]
Is anyone still using gitter?

**Comment by chmorgan** [comment]
@Phyxion should we use slack instead? I was copying what we have for sharppcap which is pretty quiet but wanted it to be available.

**Comment by Phyxion** [comment]
GitHub discussions will be available soon, might be worth waiting a bit and then enabling that. That way everybody will have a benefit of it.

**Comment by chmorgan** [comment]
Plan is to hold on this and use GitHub discussions that @PhyxionNL mentioned. Keeping this open until then.

**Comment by PhyxionNL** [comment]
GitHub Discussions should now be available @chmorgan, you can enable this in the repo settings. So closing this.

**Pull request closed without merging**
