### PR TITLE
Null support

### PR DESCRIPTION
**Pull request by chmorgan**
@hsluoyz would you mind reviewing the null portion of this pull request?

### CODE REVIEW

**Comment by hsluoyz** [comment]
There's still a bug. The loopback TCP packets are not recognized as TCP.

**Comment by chmorgan** [comment]
@hsluoyz can you be more specific about the issue? I've updated the null unit test and the packet type hierarchy looks correct here. I pushed out an improved unit test version for review.

**Comment by hsluoyz** [comment]
Please run ``Example6.DumpTCP.exe`` and capture on ``Npcap Loopback Adapter``. It is supposed to see some TCP traffic, because there are always some TCP packets for loopback interface. However, it shows nothing. I found in ``GetInnerPayload()`` function of ``InternetLinkLayerPacket.cs``, the code doesn't think the TCP packets with DLT_NULL header is actually a TCP packet. So DumpTCP doesn't show it. However, it's wrong.

**Comment by chmorgan** [comment]
Ahh right.

Let me fix those deprecated calls to GetEncapsulated() and switch to
Packet.Extract() instead. That should fix the issue and potentially let me
remove InternetLinkLayerPacket.GetInnerPayload() which was hacky in the
first place.

I'll take a look at this tonight. Appreciate the feedback. I've been idle
on the project for a while but for some reason have been interested in
fixing things up a bit now and want to grind through that stuff over the
next week or so and maybe when I'm on vacation this next week as well.

**Comment by hsluoyz** [comment]
Thanks. And please add the Npcap mode support first. Because I usually don't install Npcap with WinPcap compatible mode. And this doesn't work with SharpPcap by now.

**Comment by chmorgan** [comment]
I'll see what I can do. I need to check to see what the implication of
changing the dll directory is under Mono on Linux. Npcap isn't used there
but if this dll mapping doesn't work correctly I'll have to do that
directory change based on the running environment instead. So it will be a
little bit of testing before that will be implemented. I'm hoping to work
on it in the next few days or week at the latest.

Chris

**Comment by cameron-elliott** [comment]
Chris, this is a great fix, especially considering Wireshark on Windows switched from winpcap to npcap as the default in the latest Wireshark release just under a month ago.
Just a note FYI, it doesn't look like the last Packetnet release includes these changes.
Although, it looks like the Packetnet DLL is bundled in the latest Sharppcap release, so I think I am able to get ahold if it that way.

**Comment by chmorgan** [comment]
Hi @cameron-elliott how are you using packetnet, through nuget? Nuget should have the latest version available.

**Comment by chmorgan** [comment]
Yeah and this was merged in 2017, a long long time ago, it must be in the latest packetnet releases on nuget. That's really where most of the releases are these days, not here in the releases of the project. From what I can tell almost everyone is using nuget.

**Comment by cameron-elliott** [comment]
Silly me, I presumed the github releases tab would correspond to the nuget releases, which I obviously didn't look at, but should have!
Thanks for pointing that out. 
Apologies for not noticing that, and filing an issue.
:+1:

**Pull request merged**
