### PR TITLE
Add ISourceDestinationPort to unify access to TCP and UDP ports.

### PR DESCRIPTION
**Pull request by pluskal**
Add ISourceDestinationPort to unify access to TCP and UDP ports. It simplifies usage without a need to cast each packet to be particular type TCP or UDP.

### CODE REVIEW

**Comment by Phyxion** [comment]
Can't this just be added to TransportPacket instead? I don't think anything else but TCP/UDP uses it.

**Comment by pluskal** [comment]
Sure it could be. But I think that ```TransportPacket``` should be removed in future in case that another transport protocol that does not have checksum is implemented or it breaks OOP.

Also, not all transport protocols have [ports](https://networkengineering.stackexchange.com/questions/45550/are-there-any-transport-layer-protocol-without-the-concept-of-port)

New C# have concrete method implementation in an interface so it could be substituted by an interface.

**Comment by Phyxion** [comment]
True, but at the moment only these packets use it. I think if this ever gets added it can be separated then. For example, `TransportPacket` also contains a `Checksum`, I doubt all transport packets would have that as well.

**Comment by pluskal** [comment]
Is not this a reason to remove ```TransportPacket``` in favor of interface? It breaks Open/Close principle to implement it into ```TransportPacket```. You would close it to an extension in future and also breaks Liskov Substitution Principle because of checksum and ports would break substitution into existing code.

**Comment by Phyxion** [comment]
Yes, probably, but that will likely break quite some existing projects. I'm not opposed to adding some abstraction regarding SourcePort and DestinationPort, but as the `TransportPacket` is currently only for TCP/UDP I don't think it's very beneficiary to add an interface _at this point_.

**Pull request closed without merging**
