### PR TITLE
Cameron pr

### PR DESCRIPTION
**Pull request by cameron-elliott**
I have made the following changes:
- created both an Ipv4 and Ipv6 icmp pcap file with raw link layer from the previous ethernet link layer pcaps to support the unit tests
- Upgraded NUnit from 2.4.x to version 2.6.3 so it can support TestCaseAttribute
- Modified the ipv4 and ipv6 Icmp tests so they will test both ethernet pcap files and raw pcap files.
- Fixed an issue in the code of the original PR, resolving a bug.
- Added some explanatory text to how IPv4 vs IPv6 is detected since Raw lacks headers

### CODE REVIEW

**Comment by cmo-hms** [comment]
Could you combine the appveyor.yml changes together? (Which I presume would result in no commits adding or removing appveyor.yml)

Also, the merge at the last commit seems odd if chmorgan:cameron_pr is the starting point for your changes, I'm not sure why that merge is in the commit list.

What is the 'x' commit?

(I can merge 1865f50 into the initial commit when I process the branch)

Once you've cleaned the branch up I'll take a look at the actual commits.

**Comment by cameron-elliott** [comment]
Chris,
Sorry it is so messy, I am not very proficient at git, I found a
stackoverflow page on how to edit/squash
PR's, so I will work with that to get the PR a bit more pretty and
incorporating your comments.
Thank you for being patient with my git inexperience.
Cameron

Cameron Elliott
Lime Video Software  206-310-3284
www.limevideo.com
Digital Video SDKs for C# - .NET for Windows - Mono for Linux

**Comment by cameron-elliott** [comment]
Thanks for your patience. I learned about 'git rebase -i', nifty.
Things should be in better shape now.
Please let me know if you would like another change.

**Comment by cameron-elliott** [comment]
Okay, I think stuff is in good shape.
If you like, I can add appveyor.yml, and then you could see the unit test output as a double check before accepting the PR. Or we could do the appveyor stuff in another PR.

**Comment by chmorgan** [comment]
@cameron-elliott I think either approach works for me. It does seem separate from this pull request so a separate pull request probably makes the most sense.

**Comment by cameron-elliott** [comment]
Cool, then I think this is ready for your review and suggestions or commit.

**Pull request closed without merging**
